### ISSUE TITLE
Implement write-side operations for IGC Repository Connector

### ISSUE THREAD

**Issue by cmgrote** [odpi/egeria-connector-ibm-information-server#18]
Anyone have a particular priority they're after?

- [x] addRelationship
- [x] purgeRelationship
- [x] classifyEntity
- [x] declassifyEntity
- [ ] ~addEntity~
- [x] updateEntityProperties
- [ ] updateEntityClassification
- [x] purgeEntity

**Comment by planetf1** [comment]
I presume this is likely superceeded by any egeria integration done by the product team. Is this just a placeholder to monitor how that goes in case we need to add more support in the egeria connector?

**Comment by cmgrote** [comment]
Precisely

**Comment by cmgrote** [comment]
Per #26 if we do implement `addEntity` then that is where we should validate statuses (and if we're trying to add with a status that we do not support, then there to throw an exception).

**Comment by cmgrote** [comment]
Next priorities should be the CRUD operations related to non-reference-copy entities.

**Comment by cmgrote** [comment]
Some intricacies still to handle:

- [ ] need to specify a default category as part of connector config, as it is not possible to create new terms in IGC without a `parent_category` (and not possible via Egeria to create an entity with an initial set of relationships that would give the `parent_category`) -- probably need this to be a root-level category name, and auto-create the category first if it does not exist (because we'll need its RID to put into `parent_category` of the term's create request)
- [ ] allow optionally specifying the default IGC term `status` as part of connector config, also required when creating a term (and should probably fall-back to defaulting it as `CANDIDATE` to match IGC UI behaviour)

**Comment by cmgrote** [comment]
Actually, it's looking likely that supporting `addEntity` will not be possible as IGC does not have a way to control `qualifiedName` and ensure it is unique across potential entry points (eg. OMRS API, its own REST API directly and the UI).

See https://github.com/odpi/egeria/issues/2010 for more details on expected `qualifiedName` behaviour.

**Comment by grahamwallis** [comment]
The other repositories do not necessarily police uniqueness - because instances can arrive from across the cohort. The ethos is to tolerate, but raise the alarm and invoke corrective action.

**Comment by grahamwallis** [comment]
The other repositories do not necessarily police uniqueness - because instances can arrive from across the cohort. The ethos is to tolerate, but raise the alarm and invoke corrective action.

**Comment by cmgrote** [comment]
There aren’t any hook points for IGC to identify this and “raise an alarm”, even for the instances that are homed in IGC itself; so I still think the risk outweighs any benefit (of the very few types that can even technically be created, as well as in light of their other limitations vis-a-vis property gaps or mismatches relative to the standard types across the entity instance itself, relationship instances, etc).

**Comment by mandy-chessell** [comment]
@cmgrote The list of valid statuses for a type are defined in the TypeDef.  If the type includes statuses that IGC does not support then it does not support the type and should respond appropriately in verifyTypeDef.  Then it will not be called for addEntity/addRelationship by Egeria.  If talking to a different implementation of OMRS them may get called and should return with an invalid type exception

**Comment by mandy-chessell** [comment]
A repository should validate that unique properties such as qualifiedName are unique within the repository at the time of creation.  This does not mean they are unique across the cohort.  The repository can choose whether to store an incoming instance from another member of the cohort is the qualified name clashes.  The stewardship server with be scanning and looking for duplicates.  Duplicates will be linked together by the stewardship server and notifications made.  The repositories themselves are not responsible for this deduplication effort.  The OMASs may make use of the linked duplicate entities to show a broader report - eg asset lineage will do that

**Comment by cmgrote** [comment]
> The list of valid statuses for a type are defined in the TypeDef. If the type includes statuses that IGC does not support then it does not support the type and should respond appropriately in verifyTypeDef. Then it will not be called for addEntity/addRelationship by Egeria. If talking to a different implementation of OMRS them may get called and should return with an invalid type exception

I thought we had revisited this in light of the potential for read-only connectors that home a particular piece of metadata, that they should be able to still support whatever limited set of statuses (and properties) they support for a given type, so long as all mandatory ones are there.  Since the others are optional, this would mean that a read-only connector can still participate in a cohort -- it would only impact that connector's ability to properly be able to home new instances (via `addEntity` and the like), but that we could verify this further detail as part of the `addEntity` and if not able to support a given status or property then we could throw a `FunctionNotSupportedException` at that stage.  I'm trying to find the issue where we captured this, but I can see from my code that I had originally done validation of all of the statuses, etc in `verify` but then had commented it out suggesting it be moved to `addEntity` etc based on this previous discussion...

If we're reverting that and now saying that `verify` itself should already suggest whether something is fully-supported or not (ie. all of its optional properties and statuses), even for a read-only connector, then I believe the number of types we can support from IGC is going to be drastically reduced, unnecessarily...

> A repository should validate that unique properties such as qualifiedName are unique within the repository at the time of creation.

Precisely: IGC has no way to do this.  While we could put in our own check as part of `addEntity` for the APIs of Egeria, there is no way to enforce the same check for other routes through which metadata can be added to IGC, namely its own REST API and its UI -- even when IGC is the lone member in a cohort and reference copies are not involved.

**Comment by mandy-chessell** [comment]
There is a big difference between being a read only connector and one that takes new entities or stores metadata.  When it comes to creating a master copy of an instance, it is important to be able to support the entire lifecycle and all of the properties before accepting the responsiblity to store the instance - it can not decide half way through an instance's lifecycle that a particular property value can not be stored - or a status is not available.  So it has to support the full type for it to accept a new instance - we want new instances to be stored in the most appropriate place and having a repository grab instances it is not fully able to support when there is a repository in the cohort that is fully competent is a problem.

The addEntity/Relationship does support FUNCTION_NOT_SUPPORTED so I would say that it would be ok to respond positively to verifyTypeDef for types that can be supported read only and then throw FUNCTION_NOT_SUPPORTED on the add instance methods to say that this type is not supported on the write operations.

-------

On the deduplication - this is why OMRS and the responsibilities for repositories have been defined that way.  I am confused as to what the problem is here?

**Comment by cmgrote** [comment]
> There is a big difference between being a read only connector and one that takes new entities or stores metadata.

Absolutely!  This is why I've been quite cagey about enabling write operations in general on IGC -- I'd need to do some deeper analysis, but the reality is that it _might_ support 1 type on the write side, and quite possibly none at all (in particular wrt `qualifiedName`)...  So not sure it really makes sense to do implement any write operations?

> The addEntity/Relationship does support FUNCTION_NOT_SUPPORTED so I would say that it would be ok to respond positively to verifyTypeDef for types that can be supported read only and then throw FUNCTION_NOT_SUPPORTED on the add instance methods to say that this type is not supported on the write operations.

Perfect, this is what I've been doing all along -- subject to some deeper analysis, I may simply _always_ throw FNS from the write operations rather than even checking (as I suspect none of the IGC types are going to be fully compliant for writes).

> On the deduplication - this is why OMRS and the responsibilities for repositories have been defined that way. I am confused as to what the problem is here?

There isn't an issue when IGC does not support the write operations.  The issue if IGC tries to support the write operations is:

- The only instance-unique information that IGC retains for an object instance is its RID (unique to that metadata repository only, not across), and the "identity characteristics" of an object instance.
- For read-only operations, I can use these "identity characteristics" to ensure there is a unique `qualifiedName` within that repository for a given object instance -- no two instances can have the same set of "identity characteristics" in that repository.
- However, this set of characteristics is fixed, by object type, by IGC.  And they span the composition of various objects (eg. for a database column it is the combination of host, schema, database, table and column).
- To allow a caller to set any arbitrary `qualifiedName` they want in IGC, I wouldn't be able to use these "identity characteristics" -- we'd need to introduce our own property or attribute to capture this.
- While we could (in theory) introduce a custom attribute to capture these caller-provided `qualifiedName`s, there is nothing in IGC to enforce uniqueness of a custom attribute's values.
- While we could (in theory) do a "search-first, update-if-found / add-if-not" semantic against this custom attribute in `addEntity`, etc of the OMRS API, there is no hook-point for us to enforce the same semantic for either IGC's native REST API or its UI.  Therefore, any non-Egeria caller / user could arbitrarily create non-unique `qualifiedName` values across object instances in the same IGC repository -- and there is nothing we could technically do to even check this, let alone prevent it.
- The only thing we could do is constantly "poll", across the entire set of metadata in the repository, to try to reactively detect non-unique names, on a periodic basis.  I think this very quickly would not scale...
- Hence my suggestion that we do not support write operations in IGC.

**Comment by cmgrote** [comment]
After further consideration and discussion during 03/12 - 04/12 meetings in Amsterdam, will no longer be implement metadata maintenance operations for IGC due to:

- Inability to create more than 5-6 types in IGC via its APIs
- When considering property overlap between these and the open types, the list is further reduced to perhaps just a couple of types
- Since we cannot capture properties on relationships in IGC, this means that such entity instances would furthermore be standalone (not very useful)
- And therefore the impact of maintaining such operations is likely to largely outweigh any (minimal) benefit to be gained from implementing them
