### ISSUE TITLE
IGC Repo Proxy - SemanticAsignment triggers multiple events

### ISSUE THREAD

**Issue by ruxandraRosu** [odpi/egeria-connector-ibm-information-server#19]
A semantic assignment triggers multiple OMRS events: UPDATED_ENTITY(3), NEW_RELATIONSHIP(1), UPDATED_RELATIONSHIP(2).
Are all events necessary? This could add some overhead on omrs/omas's level.

**Comment by cmgrote** [comment]
Browsing through the latest set of sample payloads (after the type simplification from `TypeEmbeddedAttribute` and `NestedSchemaAttribute`) this duplication appears to be resolved -- at least for these `SemanticAssignment` examples.

Will close for now, but suggest we open a new issue if we identify any duplication elsewhere.
