### ISSUE TITLE
 OCF-CONNECTION-500-010 Invalid Connector class

### ISSUE THREAD

**Issue by IBMIGDWH** [odpi/egeria-connector-ibm-information-server#192]
currently i am running  java -Dloader.path='/home/centos/egeria/egeria-connector-ibm-information-server-package-1.3-20200106.120036-38-jar-with-dependencies.jar' -jar egeria_server_1.3.jar
in cento 7 unix environment and but i having issue while connecting IGC below is the error 

Wed Jan 08 08:22:06 CET 2020 myserver Information OMRS-AUDIT-0001 The Open Metadata Repository Services (OMRS) is initializing
Wed Jan 08 08:22:06 CET 2020 myserver Information OMRS-AUDIT-0003 The local repository is initializing with metadata collection named myserver with an id of c0a75f07-cc8f-4af3-a706-1b98c1e2508c
Wed Jan 08 08:22:06 CET 2020 myserver Information OMRS-AUDIT-0029 The local repository outbound event manager is initializing
Wed Jan 08 08:22:06 CET 2020 myserver Exception OMRS-AUDIT-0034 The connector to the local repository failed with a org.odpi.openmetadata.frameworks.connectors.ffdc.ConnectionCheckedException exception and the following error message: OCF-CONNECTION-500-010 Invalid Connector class org.odpi.egeria.connectors.ibm.igc.repositoryconnector.IGCOMRSRepositoryConnector

can some one help to resolve this

**Comment by cmgrote** [comment]
Hi @IBMIGDWH can you please try using the instructions here exactly as written: https://github.com/odpi/egeria-connector-ibm-information-server#tldr-for-igc

If this still does not work, please provide the exact output for step 4 and each `curl ...` command (and its output) from step 5 in your environment (just remember to remove any sensitive information like passwords from the `curl ...` commands before you paste them here).

**Comment by IBMIGDWH** [comment]
i have tried to execute each and every command but it shows could not get response on each command

**Comment by cmgrote** [comment]
Likely caused by insufficient information in the logs -- related to #194, which should be resolved shortly.
