### ISSUE TITLE
Need to check for empty properties map

### ISSUE THREAD

**Issue by grahamwallis** [odpi/egeria-connector-ibm-information-server#219]
A change to RelationshipMapping in commit 09f8efc618ff35b7ce1757d8c7f04eaea1b161b6 introduced potential for an NPE during findRelationshipByProperty is a MatchProperties parameter is supplied but it has no properties.

This causes NPEs in the CTS Relationship Search tests

The fix is straightforward:

RelationshipMapping line 399 
```
if (matchProperties == null || matchProperties.getInstanceProperties().size() == 0)
```
should be extended to also check that getInstanceProperties() does not return null.

**Comment by cmgrote** [comment]
Hmmm... looks like I'd fixed it locally but hadn't pushed through in a PR
