### ISSUE TITLE
IBM-IGC connector for Egeria 2.0 is missing

### ISSUE THREAD

**Issue by zoranid** [odpi/egeria-connector-ibm-information-server#326]
Egeria 2.0 is released but there is no IGC connector for it. It is not available at any of specified locations below.
1. https://odpi.jfrog.io/odpi/egeria-release-local/org/odpi/egeria/egeria-connector-ibm-information-server-package/
2. https://odpi.jfrog.io/odpi/egeria-staging-local/
3. https://odpi.jfrog.io/odpi/egeria-snapshot-local/org/odpi/egeria/egeria-connector-ibm-information-server-package/

**Comment by planetf1** [comment]
Egeria 2.0 is currently the version in master. We updated the version just a few days ago.

It has not been released yet..

Transferring this to the connector repo

**Comment by planetf1** [comment]
note the connector build is currently failing - see https://dev.azure.com/ODPi/Egeria/_build/results?buildId=7607&view=logs&j=8be1a9ea-1eb4-5524-bf1d-a6df7ca2ef0e&t=8d97575e-cba0-5bf4-96d8-a61d91dc9985&l=281

**Comment by cmgrote** [comment]
As Nigel indicated, 2.0 is our current snapshot (not yet released).

I've just merged #327 to make use of the latest Egeria core snapshot -- snapshot builds for the connector are now available under https://odpi.jfrog.io/odpi/egeria-snapshot-local/org/odpi/egeria/egeria-connector-ibm-information-server-package/

I believe this should close the issue; if you run into other problems or I've misunderstood, feel free to raise another issue or re-open this one (with further details) as appropriate.
