### ISSUE TITLE
Rename repository to egeria-connector-ibm-information-server

### ISSUE THREAD

**Issue by cmgrote** [odpi/egeria-connector-ibm-information-server#33]
We should rename this repository to encompass IBM Information Server (the full suite) rather than just IGC.  It already covers some metadata that comes from Information Analyzer, and with the addition of the Data Engine Proxy for DataStage it's covering more and more of the suite as a whole rather than just IGC.

**Comment by cmgrote** [comment]
Hi @jmertic @schannamallu -- can one of you rename this repository to `egeria-connector-ibm-information-server` ?  I've ensured all local changes are committed at this point, so am happy to re-clone once the rename is completed.

**Comment by planetf1** [comment]
I assume there'll be changes needed in the docker scripts in egeria too?

**Comment by cmgrote** [comment]
Those changes should in theory already be done, as they pull the compiler jar file directly, which has already been renamed.

I think biggest risk will be a broken link here or there, but I’ll try to catch those via some scans.

**Comment by jmertic** [comment]
Made the change now.
