### ISSUE TITLE
IGC Admin Role for configuring the Proxy

### ISSUE THREAD

**Issue by cong78** [odpi/egeria-connector-ibm-information-server#394]
Hi Chris, 

Previously you have mentioned the IGC Admin Role will be removed in further release without uploading the bundle. 
May I ask is it already done from the current master? We don't need this role to configure the proxy anymore right?

Thanks a lot,

Cong

**Comment by cmgrote** [comment]
That's correct -- the role is only needed if you are enabling (configuring) the event mapper as part of the proxy. Leaving the event mapper switched off (not configuring it) will mean the role is not required.

**Comment by cong78** [comment]
Great! Thanks! I will close this issue as well.
