### ISSUE TITLE
Paging is not working properly

### ISSUE THREAD

**Issue by yevgenmar** [odpi/egeria-connector-ibm-information-server#421]
If page size is grate than size of result set, the result contains copies to fill up to the page size.

See org.odpi.egeria.connectors.ibm.igc.repositoryconnector.IGCOMRSMetadataCollection.findEntitiesByProperty
line 1330:                     if (pageSize == 0 || (pageSize > 0 && entityDetails.size() < pageSize)) {
entities are added to fill up entityDetails up to pageSize
  

If page size has divider of the size of result set, the function org.odpi.egeria.connectors.ibm.igc.repositoryconnector.IGCRepositoryHelper.processResultsForMapping(EntityMapping, List<EntityDetail>, ObjectCache, String, String, List<String>, SearchProperties, int, SearchClassifications, String, SequencingOrder, int)
throws at line 526: org.odpi.egeria.connectors.ibm.igc.clientlibrary.errors.IGCConnectivityException: Request failed -- check IGC environment connectivity and authentication details.

**Comment by cmgrote** [comment]
Paging may indeed have issues today; however, I wouldn't expect it to be throwing exceptions like this...  Can you confirm the version of IGC you're working against?

For example, there is a known issue in v11.5.0.2sp6 where IGC's own paging (via its REST API) basically does not work.

**Comment by cmgrote** [comment]
Mandy mentioned another issue, where if the pageSize is greater than the actual number of results (eg. a pageSize of 100 but only 5 actual results), the list seems to be filled up with duplicates to reach the full size of 100.  I'll try to reproduce on my side...

**Comment by cmgrote** [comment]
I've tried reproducing, but have not had success in replicating this last problem regarding filling-up to pageSize...

Running `findEntitiesByProperty` with the following criteria:

```json
{
	"class": "EntityPropertyFindRequest",
	"typeGUID": "0db3e6ec-f5ef-4d75-ae38-b7ee6fd6ec0a",
	"pageSize": 100,
	"matchCriteria": "ALL",
	"matchProperties": {
		"class": "InstanceProperties",
		"instanceProperties": {
			"displayName": {
				"class": "PrimitivePropertyValue",
				"instancePropertyCategory": "PRIMITIVE",
				"primitiveDefCategory": "OM_PRIMITIVE_TYPE_STRING",
				"primitiveValue": ".*\\QAddress\\E.*"
			}
		}
	}
}
```

In an environment where there are 6 such matches only returns 6 results (not the full pageSize of 100).

If I revise the query to remove any search conditions, using the following:

```json
{
	"class": "EntityPropertyFindRequest",
	"typeGUID": "0db3e6ec-f5ef-4d75-ae38-b7ee6fd6ec0a",
	"pageSize": 100
}
```

... in an environment with 43 terms, I again only receive 43 results in the response (not the full pageSize of 100).

The particularly line of code referenced (line 1330 in `IGCOMRSMetadataCollection.findEntitiesByProperty`) exists to short-circuit the search process if there is _already_ a full page of results (by avoiding running additional searches when the results of those additional searches would not end up on the page requested by the user anyway).

I've also, in the latest master for the connector, changed the various RuntimeExceptions (like `IGCConnectivityException`) over to checked exceptions, and these should all now be converted into `RepositoryErrorExceptions` and a full stack trace included.  Therefore, if you could please update the connector to the latest from master and re-run your scenario that produced that last exception we should have greater detail from the full stack trace on precisely what the error is (it appears to be something problematic at the IGC REST API level based on what the Java client is trying to communicate to it -- but the full stack should include details on what it attempted to request and the error from IGC's side (401, 403, 500, etc)).

**Comment by cmgrote** [comment]
Perhaps we've misunderstood that last point, though -- I can see that if I cycle through pages of results (eg. pageSize of 2 in the scenario above where there are actually 43 results), regardless of the page I request (by changing the `"offset"`), each page contains the same 2 results.  I'm assuming that this is the actual first issue?
