### ISSUE TITLE
DataStage proxy user authorization issue

### ISSUE THREAD

**Issue by AlexCostoiu** [odpi/egeria-connector-ibm-information-server#424]
Hi Chris,

We have tried to run and test the DS proxy with an NPA user with the following roles:

•	Information Governance Catalog User
•	Suite User

The issue is that we get a not authorized error when trying to detect the flows of a job by RID:
for https://<<hostname>>/ibm/iis/igc-rest/v1/flows/detectFlows/dsjob/<<RID>>
error: 403 Forbidden: [{"message":"User is not authorized to perform this operation","code":403}]

Do we need more roles for the user for the proxy to be able to detect these flows? Is it probably some Administrator role for Datastage assets? Or is it another cause for it?

Thanks,
Alex

**Comment by cmgrote** [comment]
Hi @AlexCostoiu -- I suspect you're using v11.7 of Information Server for this test?  Per the updated README:

> For v11.7 and above, the user will also need the Information Governance Catalog Asset Administrator role in order to automate the detection of lineage within IGC, prior to having a complete set of lineage for the DataStage connector itself to retrieve.
