### ISSUE TITLE
No longer able to automate CTS against v11.5.x

### ISSUE THREAD

**Issue by cmgrote** [odpi/egeria-connector-ibm-information-server#456]
Information Server v11.5.x uses TLS v1.0 on the server side, which therefore cannot be accessed using the default Egeria docker images (based on OpenJDK v11, which disables TLS v1.0).

Have attempted to override this behaviour using options like `‑Djdk.tls.client.protocols="TLSv1"` and `‑Djdk.tls.server.protocols="TLSv1"` -- and can see that these are being processed as part of the startup of the OMAG within the container -- however they do not resolve the problem.

Unclear if:

- this is something that we can override / address while still using the OpenJDK v11 images (eg. via other command-line args or environment variables)
- we should no longer bother testing v11.5.x of Information Server (assuming the problem is only limited to these older versions of Information Server?)
- we should consider creating a secondary set of images based on OpenJDK v8 for such "legacy" usage

@planetf1 any thoughts?

(Note that this only impacts v11.5.x of Information Server -- v11.7.x is fine.)

**Comment by planetf1** [comment]
TLS 1.0 was deprecated in 2018 and many sites/apps disabled it in March 2020. As such I'd be inclined to stop supporting anything that cannot support a later version

**Comment by planetf1** [comment]
For example as per https://portswigger.net/daily-swig/tls-1-0-1-1-end-of-life-countdown-heads-into-the-danger-zone

 - In Oct 2018 Google, Apple, Microsoft & Mozilla agreed to deprecate the protocols by early 2020
 - By March 2019 the IETF formally issued the deprecation https://tools.ietf.org/id/draft-ietf-tls-oldversions-deprecate-02.html with the deprecation to take effect from June 30 2018 formally stating 'TLSv1.0 MUST NOT be used. Negotiation of TLSv1.0 from any version of TLS MUST NOT be permitted.'
 - In March, April 2020 various products actually dropped support on security grounds
 - A google search shows this continuing through 2020 across many vendors and stacks

Given the above, I do not think it is appropriate for us to support TLS 1.0, and thus we should no longer support integrations that require this . Notwithstanding this, if there are particular interested parties that wished to encode this support in an appropriate, and caveated way (bearing in mind also aspects like results from static and dynamic code analysis) then it could be considered.

**Comment by planetf1** [comment]
As a notes, I think adding
server.ssl.enabled-Protocols: TLSv1
as a spring property might be needed for inbound connections -- if it works --
ie add to docker
`--env SERVER_SSL_ENABLED_PROTOCOLS=TLSv1
`maybe?
