### ISSUE TITLE
IGC client library - workflowMode breaks internal paging

### ISSUE THREAD

**Issue by lpalashevski** [odpi/egeria-connector-ibm-information-server#471]
IGC Version ‎‪11.7.1SP2‬ 
Build ‎‪11.7.1SP2-dev_b164_cc72b37fee5a‬ 

When workflowMode is "true" igc client cannot retrieve next page of the results.

One example scenario is trying to retrieve relationships for entity:

Call stack:
```
org.odpi.egeria.connectors.ibm.igc.repositoryconnector.mapping.relationships.RelationshipMapping#addSearchResultsToRelationships  
org.odpi.egeria.connectors.ibm.igc.repositoryconnector.mapping.relationships.RelationshipMapping#addListOfMappedRelationships
org.odpi.egeria.connectors.ibm.igc.clientlibrary.IGCRestClient#getNextPage

```

Having workflowMode=true adds extra parameters to the next page search query:

if (this.workflowEnabled && !sNextURL.contains("workflowMode=draft")) {
    sNextURL += "&workflowMode=draft";
}

and leads to 400 "Invalid search parameters" response.

**Comment by cmgrote** [comment]
I'm not able to reproduce this manually via the API on a vanilla v11.7.1.0sp2 environment with workflow enabled:

- Searching for `term` with no conditions and a pageSize of 1, with `workflowMode=draft`, and a mixture of terms in both the workflow (draft) and outside the workflow: `/ibm/iis/igc-rest/v1/search?types=term&workflowMode=draft&pageSize=1&begin=1` returns results in all cases (never a 400 response).
- Searching for `database_column` with no conditions and a pageSize of 1, with `workflowMode=draft`, and of course in this case there is no such thing (database_columns do not participate in the workflow): `/ibm/iis/igc-rest/v1/search?types=database_column&workflowMode=draft&pageSize=1&begin=1` still returns results (both with and without the `workflowMode=draft`, and never a 400 response).

Were you able to resolve this on your side by removing this condition statement?

I'm curious what the actual URL being produced is that's causing the error, as it doesn't seem to be one of the ones above...  Or perhaps the workflow you're using in your v11.7.1.0sp2 environment does not match mine.  Did you enable the workflow using the "old" / traditional method (via the original Administration UI), or via the new micro-services based IGC UI that is only available in v11.7.x?

**Comment by lpalashevski** [comment]
I will have to get the answers on how the workflow was enabled from the production support team. 

Yes, the local change we did removing the condition statements (not having &workflowMode=draft in the query) resulted in assetlineage being able to create complete lineage context for specific term with 200+ semantic assginments (previously missing).

This is the search query request:

/ibm/iis/igc-rest/v1/search?types=main_object&where={"conditions":[{"property":"assigned_to_terms","operator":"=","value":"TERM_RID"}],"operator":"or"}&pageSize=100&begin=100&workflowMode=draft

and the response

{
    "message": "Invalid search parameters, please verify all Search operators and fields are valid",
    "code": 400
}

I will try to get more information from the environments in regards to how the workfow is configured.

**Comment by lpalashevski** [comment]
This issue is still present. Reproduced on Prod with following request:

```
https://{SERVER_NAME}:{SERVER_PORT}/ibm/iis/igc-rest/v1/search?types=category&types=data_class&types=data_file&types=data_file_field&types=data_file_folder&types=data_file_record&types=database&types=database_column&types=database_schema&types=database_table&types=host&properties=created_by&properties=created_on&properties=modified_by&properties=modified_on&sorts=SearchSort{property='_id', ascending=true}&where={"conditions":[{"property":"assigned_to_terms","operator":"=","value":"{TERM_RID}"}],"operator":"or"}&pageSize=100&begin=100&workflowMode=draft 
```

Response:
```
{
    "message": "Invalid search parameters, please verify all Search operators and fields are valid",
    "code": 400
}
```

Still unknown how the environement is configured, no feedback from the support team.

**Comment by lpalashevski** [comment]
@cmgrote

I've managed to check the workflowMode on the named environment using the API.

`GET /ibm/iis/igc-rest/v1/workflow/status`
 
```
{
    "assetTypes": [],
    "workflowMode": "CLASSIC_ON",
    "isWorkflowEnabled": true
}
```

Same check on the environment where the same query works:

```
{
    "assetTypes": [],
    "workflowMode": "OFF",
    "isWorkflowEnabled": false
}
```

Can we use this info or call the same endpoint on connector startus to retrieve workflowMode? 
Then, if we can improve query in generic way that works irrespective of how it is configured per environment.

**Comment by lpalashevski** [comment]
Update:

After extensive test performed against multiple environments using IGC API, I can conclude following:

1. Bad request 400 error is not directly caused because of presence of `workflowMode=draft` parameter like it was originally assumed but in combination with other paging parameters like `pageSize` and `begin`. In cases where there are no results returned (mostly because `workflowMode=draft` see point 2) paging parameters like in the example below can cause 400. 
Example: 

- `/search?pageSize=1&begin=1&workflowMode=draft` - responds wiht 400 because page 1 does not exists (no results returned).
- `/search?pageSize=1&begin=1` - responds 200 returns results properly.

2.  The IGC REST API documentation for GET /search and workflowMode parameter says: 
`Enter 'draft' without the quotation marks to search the catalog and the development glossary. When this field is blank, only the catalog is searched.` - This is not true based on the behaviour observed. When workflowMode=draft catalog items are not returned (there can be environments with workflow enabled not having any items in development glossary-such example is the prod environment where the issue appeared originally). 


Based on above I propose following solutions:

a) Remove workflowMode from nextPage method implementation;

b) Additionally to a) remove it completely the base getQuery as well since we do not really see use cases where development glossary is important;

b) Make workflowMode configuration parameter so the administrators can enable it when needed per environment (instead of connector dinamically querying if the workflow is enabled on startup).

cc: @cmgrote

**Comment by lpalashevski** [comment]
Additional testing shows that this problem cannot be reproduced on the latest version:

Version ‎‪11.7.1.1SP2‬
Build ‎‪11.7.1.1SP2-11711SP2_b94_c2917e43ba4a‬ 

Closing the issue, no longer relevant.
