### ISSUE TITLE
Lack of context for data_files without data_file_folders

### ISSUE THREAD

**Issue by lcpopa** [odpi/egeria-connector-ibm-information-server#476]
Hello

Context: when clicking on a TabularColumn node in vertical lineage of a GlossaryTerm, we expect to see its full context from a TabularSchemaType all the way to the Connection. However, this chain is broken by only displaying the Schema and DataFile (see img)
 
<img width="1680" alt="Screenshot 2021-01-26 at 12 51 11" src="https://user-images.githubusercontent.com/46932180/106435546-b4159380-647b-11eb-9859-c059a0aa26a8.png">
 
Possible cause: by debugging, managed to reach the point where igc-proxy interrogates for the relationship between a DataFile and the folder it is stored in, but nothing is returned, therefore the issue. Need your help with confirming and eventually dealing with this. Or I am totally missing the point ? 😊
There was a suspicion amongst us that upgrading IGC from 11.5 to 11.7 might have something to do with it

**Comment by cmgrote** [comment]
I'm not sure that a DataFile will always be contained inside a folder -- could you verify inside IGC itself, for this example asset, whether it is in a folder or simply directly attached to a host?  (If you can provide a redacted screenshot from IGC of the asset that might help further diagnose the root cause.)

**Comment by lcpopa** [comment]
For this particular case, the DataFile is inside a FileFolder. Will provide the screenshot as soon as possible

**Comment by lcpopa** [comment]
From Chris: "Yes, looks like what we discussed -- the data file is linked directly to the host, not any folder objects, so the representation that's been pushed across (without any folder) I believe is accurate."

Question: Would it be appropriate for Egeria to create those Folder entities with the necessary relationships, based on the property found in the DataFile ?

**Comment by cmgrote** [comment]
Agreed on call to ensure that in cases like this (where there is a data_file linked directly to a host, without data_file_folders in-between) that we still send a `ConnectionToAsset` relationship between the `DataFile` and the `Connection` and appropriate relationship between the connection and the host (`Endpoint`) -- so that we still relate up the chain the way we do for other areas.

**Comment by cmgrote** [comment]
On further investigation, even that solution does not appear to be possible.  For these `DataFile`s that link directly to a host (without `FileFolder`s), there is no connection involved -- all we have in IGC is the `DataFile` and the `Endpoint` (no IGC `data_connection` object, which would be required to map to the `ConnectionToAsset` relationship in-between).

And in hindsight, this is probably a "good thing":

- these `DataFile` assets without any link to a `FileFolder` are typically the result of a metadata extract from one environment being loaded into another.
- as part of the import of such metadata in IGC, these `DataFile` assets are _always_ placed under the hostname of the engine tier of the environment the metadata was imported into -- irrespective of where the files themselves actually exist.
- therefore, if we _were_ to send through that these files actually exist on the host they appear under in IGC, it would look as if all of these files exist (only) on the engine tier of the Information Server host where they were _imported_ (not where they actually exist).

The reality is that the files themselves actually only exist on some other system, so if we were to suggest that they files existed on the host they appear under in IGC this would probably be a misrepresentation anyway (?)

I would suggest that to properly resolve this problem, therefore, we likely need to think more broadly about the intended use and interpretation of such `DataFile`s.

**Comment by cmgrote** [comment]
Discussed on 18/02 call -- agreed that if the proper endpoint is simply no longer there in the target IGC (which it is not, in target IGC you are always seeing the engine tier of the target environment and the source -- where the file actually exists -- is not in the target IGC) then there isn't really anything we can do to display it.

**Comment by lcpopa** [comment]
Agree to close

**Comment by cmgrote** [comment]
With https://github.com/odpi/egeria-connector-ibm-information-server/pull/497 the path of the file is now placed in to the `pathName` property of the `DataFile` object.
