### ISSUE TITLE
Add differentiation between primary and secondary categories

### ISSUE THREAD

**Issue by cmgrote** [odpi/egeria-connector-ibm-information-server#491]
- needs to be on a property of the `TermCategorization` relationship (since the same category can be primary and secondary for different terms)
- should make use of some further additional properties that could be inherited from a root RelationshipDef, after https://github.com/odpi/egeria/issues/4724

**Comment by lcpopa** [comment]
Hi Chris,

Discussed amongst ourselves the timeline aspect of the generic solution and given its uncertainty, we concluded that the immediate solution is needed. Is this issue supposed to cover that ?

Thank you

**Comment by cmgrote** [comment]
Closing as duplicate of #494 (?)
