### ISSUE TITLE
IGC repository connector - validation for instance properties mapped with wrong primitive type

### ISSUE THREAD

**Issue by lpalashevski** [odpi/egeria-connector-ibm-information-server#542]
Related to example: https://github.com/odpi/egeria/issues/5234

We need to investigate if we also need to implement outbound validation for instance property types.

**Comment by cmgrote** [comment]
Specific example of where it has gone wrong is that a minimum length is mapped as a string rather than an integer.

**Comment by cmgrote** [comment]
@lpalashevski can you confirm which connector created this problematic event?  Keeping in mind that the event mapper in this open source connector is still marked as "experimental", and looking at the linked example payload given above (which appears to have the RID as a GUID), it does not seem that the event produced was this open source connector (?)

Looking at the logic here in the open source connector, I cannot see how this example of `minimumLength` would ever be mapped as a string unless the attribute type definition itself were defined as a string (which it is not, it is defined as an integer)...

**Comment by lpalashevski** [comment]
> @lpalashevski can you confirm which connector created this problematic event? Keeping in mind that the event mapper in this open source connector is still marked as "experimental", and looking at the linked example payload given above (which appears to have the RID as a GUID), it does not seem that the event produced was this open source connector (?)
> 
> Looking at the logic here in the open source connector, I cannot see how this example of `minimumLength` would ever be mapped as a string unless the attribute type definition itself were defined as a string (which it is not, it is defined as an integer)...

Indeed this problem occured while testing using the native IGC OMRS connector and Egeria integration. 

Based on the discussion before the issue was raised to investigate if we have similar problems in the open soruce connector mappings but as you exmaplained in the last comment this is not the case. 

Additionally opensource connector is already used in prod without any issue of this nature. I think we can safely close this.
